services:
  pool:
    image: ghcr.io/riccardobl/openagents-pool:master
    networks:
      - openagents-node-network

  translate:
    image: ghcr.io/riccardobl/openagents-translate:master-cuda
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - POOL_ADDRESS=pool
      - POOL_PORT=5000
      - TRANSFORMERS_DEVICE=0
    networks:
      - openagents-node-network

  extism-runtime:
    image: ghcr.io/riccardobl/openagents-extism-runtime-node:master
    environment:
      - POOL_ADDRESS=pool
      - POOL_PORT=5000
    networks:
      - openagents-node-network

 transformersjs:
    image: ghcr.io/riccardobl/openagents-transformersjs:master
    environment:
      - POOL_ADDRESS=pool
      - POOL_PORT=5000
    networks:
      - openagents-node-network

networks:
  openagents-node-network:
    driver: bridge