# export CF_DNS_APITOKEN="...."
# mkdir -p /srv/openagents/letsencrypt/
# echo "dns_cloudflare_api_token = $CF_DNS_APITOKEN" > /srv/openagents/letsencrypt/cf.ini
# curl https://gist.githubusercontent.com/riccardobl/118e428d9464fe6007f2c705b3346910/raw/config.sh | bash
services:

  openagents-certbot:
    image: certbot/dns-cloudflare
    volumes:
      - /srv/openagents/letsencrypt/etc:/etc/letsencrypt
      - /srv/openagents/letsencrypt/log:/var/log/letsencrypt
      - /srv/openagents/letsencrypt/lib:/var/lib/letsencrypt
      - /srv/openagents/letsencrypt/cf.ini:/etc/letsencrypt/cf.ini
    command: certonly --dns-cloudflare --dns-cloudflare-credentials /etc/letsencrypt/cf.ini -d ${DOMAIN} --dns-cloudflare-propagation-seconds 60  --non-interactive --expand --agree-tos -m $TEAM_EMAIL

  openagents-caddy:
    image: caddy:2-alpine
    restart: always
    volumes:
      - /srv/openagents/caddy/Caddyfile:/etc/caddy/Caddyfile
      - /srv/openagents/letsencrypt/etc:/etc/letsencrypt
    ports:
      - "7777:7777"
    networks:
      - openagents-mvp-network

  openagents-nostr-relay:
    image: ghcr.io/hoytech/strfry:latest
    restart: always
    volumes:
      - /srv/openagents/nostr-relay/strfry.conf:/etc/strfry.conf
      - /srv/openagents/nostr-relay/data:/app/strfry-db
    networks:
      - openagents-mvp-network
   

  openagents-pool:
    image: ghcr.io/riccardobl/openagents-pool:master
    restart: always
    networks:
      - openagents-mvp-network
    environment:
      - NOSTR_RELAYS=${NOSTR_RELAYS}
      - SERVER_CRT=/etc/letsencrypt/live/${DOMAIN}/fullchain.pem
      - SERVER_KEY=/etc/letsencrypt/live/${DOMAIN}/privkey.pem
    volumes:
      - /srv/openagents/pool/blobs:/blobs
      - /srv/openagents/letsencrypt/etc:/etc/letsencrypt
    ports:
      - "5000:5000"


  openagents-extism-runtime:
    image: ghcr.io/riccardobl/openagents-extism-runtime-node:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
      - SECRETS_PROVIDERS=/secrets/secrets.json
    volumes:
      -  /srv/openagents/extism-runtime/secrets:/secrets
    networks:
      - openagents-mvp-network

  openagents-search:
    image: ghcr.io/riccardobl/openagents-search:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
    volumes:
      - /srv/openagents/search/cache:/cache
    networks:
      - openagents-mvp-network

    
  openagents-embeddings:
    image: ghcr.io/riccardobl/openagents-embeddings:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
      - CACHE_PATH=/cache
      - TRANSFORMERS_DEVICE=${EMBEDDING_DEVICE}
      - MODEL=${EMBEDDING_MODEL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - /srv/openagents/embeddings/cache:/cache
    networks:
      - openagents-mvp-network

  openagents-retrieval:
    image: ghcr.io/riccardobl/openagents-document-retrieval:master
    restart: always
    environment:
      - POOL_ADDRESS=${POOL_ADDRESS}
      - POOL_PORT=${POOL_PORT}
      - POOL_SSL=${POOL_SSL}
    volumes:
      - /srv/openagents/retrieval/cache:/cache
    networks:
      - openagents-mvp-network

networks:
  openagents-mvp-network:
    driver: bridge