# curl https://gist.githubusercontent.com/riccardobl/118e428d9464fe6007f2c705b3346910/raw/7fa5901bcb2bce7ab060b776924c441b12542a22/download-config.sh | bash
services:

  openagents-pool:
    image: ghcr.io/riccardobl/openagents-pool:master
    restart: always
    networks:
      - openagents-rblb-network
    environment:
      - BLOB_STORAGE_PATH=/blobs
      - NOSTR_RELAYS=wss://nostr.rblb.it:7777
    volumes:
      - /srv/openagents/pool/blobs:/blobs
    ports:
      - "2083:5000"
      - "2087:5001"
      - "2096:5002"

  openagents-extism-runtime:
    image: ghcr.io/riccardobl/openagents-extism-runtime-node:master
    restart: always
    environment:
      - POOL_ADDRESS=openagents-pool
      - POOL_PORT=5000
      - SECRETS_PROVIDERS=/secrets/secrets.json
    volumes:
      -  /srv/openagents/extism-runtime/secrets:/secrets
    networks:
      - openagents-rblb-network
    

  openagents-search:
    image: ghcr.io/riccardobl/openagents-search:master
    restart: always
    environment:
      - POOL_ADDRESS=openagents-pool
      - POOL_PORT=5000
      - CACHE_PATH=/cache
    volumes:
      - /srv/openagents/search/cache:/cache
    networks:
      - openagents-rblb-network

    
  openagents-embeddings:
    image: ghcr.io/riccardobl/openagents-embeddings:master-cuda
    restart: always
    environment:
      - POOL_ADDRESS=openagents-pool
      - POOL_PORT=5000
      - CACHE_PATH=/cache
      - TRANSFORMERS_DEVICE=-1
    volumes:
      - /srv/openagents/embeddings/cache:/cache
    networks:
      - openagents-rblb-network
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]

  openagents-retrieval:
    image: ghcr.io/riccardobl/openagents-document-retrieval:master
    restart: always
    environment:
      - POOL_ADDRESS=openagents-pool
      - POOL_PORT=5000
      - CACHE_PATH=/cache
      - TRANSFORMERS_DEVICE=-1
    volumes:
      - /srv/openagents/retrieval/cache:/cache
    networks:
      - openagents-rblb-network

  openagents-translate:
    image: ghcr.io/riccardobl/openagents-translate:master-cuda
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            count: 1
            capabilities: [gpu]
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=0
      - POOL_ADDRESS=pool
      - POOL_PORT=5000
      - TRANSFORMERS_DEVICE=0
    networks:
      - openagents-rblb-network


networks:
  openagents-rblb-network:
    driver: bridge